//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITG.Brix.Users.Application.Resources
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationFailures
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationFailures()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITG.Brix.Users.Application.Resources.ValidationFailures", typeof(ValidationFailures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First name must begin with a capitalized letter.
        /// </summary>
        public static string FirstNameCapitalizedFirstLetter
        {
            get
            {
                return ResourceManager.GetString("FirstNameCapitalizedFirstLetter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First name length must be between 3 and 20 characters.
        /// </summary>
        public static string FirstNameLength
        {
            get
            {
                return ResourceManager.GetString("FirstNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First name cannot be null or empty.
        /// </summary>
        public static string FirstNameMandatory
        {
            get
            {
                return ResourceManager.GetString("FirstNameMandatory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First name must contain only letters and single spaces.
        /// </summary>
        public static string FirstNameOnlyLettersAndSingleSpacesAllowed
        {
            get
            {
                return ResourceManager.GetString("FirstNameOnlyLettersAndSingleSpacesAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last name must begin with a capitalized letter.
        /// </summary>
        public static string LastNameCapitalizedFirstLetter
        {
            get
            {
                return ResourceManager.GetString("LastNameCapitalizedFirstLetter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last name length must be between 3 and 20 characters.
        /// </summary>
        public static string LastNameLength
        {
            get
            {
                return ResourceManager.GetString("LastNameLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last name cannot be null or empty.
        /// </summary>
        public static string LastNameMandatory
        {
            get
            {
                return ResourceManager.GetString("LastNameMandatory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last name must contain only letters and single spaces.
        /// </summary>
        public static string LastNameOnlyLettersAndSingleSpacesAllowed
        {
            get
            {
                return ResourceManager.GetString("LastNameOnlyLettersAndSingleSpacesAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login cannot be null or empty.
        /// </summary>
        public static string LoginCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("LoginCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login must begin with a letter.
        /// </summary>
        public static string LoginFirstLetter
        {
            get
            {
                return ResourceManager.GetString("LoginFirstLetter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login length must be between 3 and 30 characters.
        /// </summary>
        public static string LoginLength
        {
            get
            {
                return ResourceManager.GetString("LoginLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login manadatory.
        /// </summary>
        public static string LoginMandatory
        {
            get
            {
                return ResourceManager.GetString("LoginMandatory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password cannot be null or empty.
        /// </summary>
        public static string PasswordCannotBeEmpty
        {
            get
            {
                return ResourceManager.GetString("PasswordCannotBeEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login length must be between 8 and 30 characters.
        /// </summary>
        public static string PasswordLength
        {
            get
            {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password mandatory.
        /// </summary>
        public static string PasswordMandatory
        {
            get
            {
                return ResourceManager.GetString("PasswordMandatory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character.
        /// </summary>
        public static string PasswordSpecial
        {
            get
            {
                return ResourceManager.GetString("PasswordSpecial", resourceCulture);
            }
        }
    }
}
